apiVersion: v1
kind: Service
metadata:
  name: controller-manager-api
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kube-freeze-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: kube-freeze-operator
  ports:
    - port: 8082
      targetPort: api
      name: api
      protocol: TCP
